/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.MenuControl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import model.Menu;

/**
 *
 * @author yobel
 */
public class DisplayMenuMainPanel extends JPanel {
    private MenuControl mc;
    private ArrayList<Menu> menuList;
    /**
     * Creates new form DisplayMenuMainPanel
     */
    public DisplayMenuMainPanel() {
        mc = new MenuControl(); 
        menuList = new ArrayList<>(mc.showListMenu()); 
        setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10)); // Menggunakan FlowLayout dengan perataan ke kiri dan margin 10px
        initMenuDisplay();
        this.setBackground(new Color(255,218,182));
    }
    
    private void initMenuDisplay() {
      for (Menu menu : menuList) {
            JPanel menuPanel = new JPanel(new BorderLayout());
            menuPanel.setPreferredSize(new Dimension(226, 200)); // Set ukuran preferensi untuk panel
            menuPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
            menuPanel.setBackground(new Color(240, 240, 240));
            
            
            JPanel infoPanel1 = new JPanel();
            infoPanel1.setLayout(new GridLayout(1, 1));
            infoPanel1.setBackground(new Color(240, 240, 240));
            infoPanel1.setBorder(new EmptyBorder(20, 5, 5, 5));
            
            // Menampilkan gambar
            JLabel imageLabel = new JLabel();
            imageLabel.setHorizontalAlignment(JLabel.CENTER);
            imageLabel.setBorder(new EmptyBorder(5, 5, 5, 5));
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(menu.getGambar()).getImage().getScaledInstance(150, 100, Image.SCALE_SMOOTH));
            imageLabel.setIcon(imageIcon);
            menuPanel.add(imageLabel, BorderLayout.CENTER);

            // Menampilkan informasi menu
            JPanel infoPanel2 = new JPanel();
            infoPanel2.setLayout(new GridLayout(2, 1));
            infoPanel2.setBackground(new Color(240, 240, 240));
            infoPanel2.setBorder(new EmptyBorder(5, 5, 15, 5));
            
            JLabel namaMenuLabel = new JLabel(menu.getNama_menu());
            namaMenuLabel.setHorizontalAlignment(JLabel.CENTER);
            namaMenuLabel.setFont(new Font("Arial", Font.BOLD, 13));

            JLabel jenisMenuLabel = new JLabel("Kategori : " + menu.getJenis_menu());
            jenisMenuLabel.setHorizontalAlignment(JLabel.CENTER);
            jenisMenuLabel.setFont(new Font("Arial", Font.PLAIN, 12));
            
            JLabel hargaLabel = new JLabel("Harga : " + menu.getHarga());
            hargaLabel.setHorizontalAlignment(JLabel.CENTER);
            hargaLabel.setFont(new Font("Arial", Font.PLAIN, 12));
            
            infoPanel1.add(namaMenuLabel);
            infoPanel2.add(jenisMenuLabel);
            infoPanel2.add(hargaLabel);
            menuPanel.add(infoPanel2, BorderLayout.SOUTH);
            menuPanel.add(infoPanel1, BorderLayout.NORTH);
            
            add(menuPanel);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 218, 182));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1231, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
