/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;


import java.awt.Component;
import javax.swing.JOptionPane;


public class karyawanMainPanel1 extends javax.swing.JPanel {

    String actionCustomer = null;
    int idCustomer = 0;
    private Component rootPane;
    
    public karyawanMainPanel1() {
        initComponents();
        setOpaque(false);
        showCustomer();
        setComponentsCustomer(false);        
        setEditDeleteButtonCustomer(false);        
        clearTextCustomer();
    }
    
    // Customer Set Komponen
    public void setComponentsCustomer(boolean value){
        namaKaryawanInputTextField.setEnabled(value);
        gajiKaryawanInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }
    
    // Customer Set Edit Delete Button
    public void setEditDeleteButtonCustomer(boolean value){
        barukanKaryawanButton.setEnabled(value);
        hapusKaryawanButton.setEnabled(value);
    }
    
    // Customer Clear Text
    public void clearTextCustomer(){
        namaKaryawanInputTextField.setText("");
        gajiKaryawanInputTextField.setText("");
        alamatInputTextField.setText("");
        searchKaryawanInputTextField.setText("");
    }
    
    public void showCustomer(){
        karyawanTextArea.setText("List Customer: \n ============= \n"+cc.showAllStringCustomer());
    }

    public void inputKosongCustomerException() throws InputKosongException{
        if(namaKaryawanInputTextField.getText().isEmpty() || alamatInputTextField.getText().isEmpty() || gajiKaryawanInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKaryawanInputPanel = new javax.swing.JPanel();
        searchKaryawanInputLabel = new javax.swing.JLabel();
        searchKaryawanInputTextField = new javax.swing.JTextField();
        searchKaryawanInputButton = new javax.swing.JButton();
        karyawanFormPanel = new javax.swing.JPanel();
        karyawanButtonPanel = new javax.swing.JPanel();
        barukanKaryawanButton = new javax.swing.JButton();
        hapusKaryawanButton = new javax.swing.JButton();
        tambahKaryawanButton = new javax.swing.JButton();
        namaKaryawanPanel = new javax.swing.JPanel();
        namaKaryawanInputLabel = new javax.swing.JLabel();
        namaKaryawanInputTextField = new javax.swing.JTextField();
        gajiKaryawanInputPanel = new javax.swing.JPanel();
        gajiKaryawanInputLabel = new javax.swing.JLabel();
        gajiKaryawanInputTextField = new javax.swing.JTextField();
        idKaryawanInputPanel1 = new javax.swing.JPanel();
        idKaryawanInputLabel1 = new javax.swing.JLabel();
        idKaryawanTextField = new javax.swing.JTextField();
        jabatanPanel = new javax.swing.JPanel();
        jabatanLabel = new javax.swing.JLabel();
        jabatanTextField = new javax.swing.JTextField();
        simpanJabatanButton = new javax.swing.JButton();
        karyawanScrollPanel = new javax.swing.JScrollPane();
        karyawanTextArea = new javax.swing.JTextArea();

        setForeground(new java.awt.Color(255, 218, 182));

        mainPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchKaryawanInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchKaryawanInputLabel.setBackground(new java.awt.Color(51, 151, 56));
        searchKaryawanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputLabel.setText("Pencarian Karyawan");

        searchKaryawanInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        searchKaryawanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKaryawanInputTextFieldKeyTyped(evt);
            }
        });

        searchKaryawanInputButton.setBackground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKaryawanInputButton.setText("Cari");
        searchKaryawanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKaryawanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchKaryawanInputPanelLayout = new javax.swing.GroupLayout(searchKaryawanInputPanel);
        searchKaryawanInputPanel.setLayout(searchKaryawanInputPanelLayout);
        searchKaryawanInputPanelLayout.setHorizontalGroup(
            searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKaryawanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                        .addComponent(searchKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 525, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchKaryawanInputPanelLayout.setVerticalGroup(
            searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKaryawanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchKaryawanInputTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        karyawanFormPanel.setBackground(new java.awt.Color(255, 221, 186));
        karyawanFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        karyawanButtonPanel.setBackground(new java.awt.Color(255, 221, 186));

        barukanKaryawanButton.setBackground(new java.awt.Color(255, 175, 47));
        barukanKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKaryawanButton.setText("Barukan");
        barukanKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKaryawanButtonActionPerformed(evt);
            }
        });

        hapusKaryawanButton.setBackground(new java.awt.Color(237, 78, 5));
        hapusKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKaryawanButton.setText("Hapus");
        hapusKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKaryawanButtonActionPerformed(evt);
            }
        });

        tambahKaryawanButton.setBackground(new java.awt.Color(51, 151, 56));
        tambahKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKaryawanButton.setText("Tambah");
        tambahKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKaryawanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout karyawanButtonPanelLayout = new javax.swing.GroupLayout(karyawanButtonPanel);
        karyawanButtonPanel.setLayout(karyawanButtonPanelLayout);
        karyawanButtonPanelLayout.setHorizontalGroup(
            karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        karyawanButtonPanelLayout.setVerticalGroup(
            karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaKaryawanPanel.setBackground(new java.awt.Color(255, 221, 186));
        namaKaryawanPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaKaryawanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaKaryawanInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        namaKaryawanInputLabel.setText("Nama Karyawan");

        namaKaryawanInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        namaKaryawanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaKaryawanInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKaryawanInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaKaryawanPanelLayout = new javax.swing.GroupLayout(namaKaryawanPanel);
        namaKaryawanPanel.setLayout(namaKaryawanPanelLayout);
        namaKaryawanPanelLayout.setHorizontalGroup(
            namaKaryawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKaryawanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKaryawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKaryawanInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaKaryawanPanelLayout.setVerticalGroup(
            namaKaryawanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKaryawanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKaryawanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gajiKaryawanInputPanel.setBackground(new java.awt.Color(255, 221, 186));
        gajiKaryawanInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        gajiKaryawanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        gajiKaryawanInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        gajiKaryawanInputLabel.setText("Gaji Karyawan");

        gajiKaryawanInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        gajiKaryawanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout gajiKaryawanInputPanelLayout = new javax.swing.GroupLayout(gajiKaryawanInputPanel);
        gajiKaryawanInputPanel.setLayout(gajiKaryawanInputPanelLayout);
        gajiKaryawanInputPanelLayout.setHorizontalGroup(
            gajiKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiKaryawanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gajiKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gajiKaryawanInputPanelLayout.createSequentialGroup()
                        .addComponent(gajiKaryawanInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(gajiKaryawanInputTextField))
                .addContainerGap())
        );
        gajiKaryawanInputPanelLayout.setVerticalGroup(
            gajiKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiKaryawanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gajiKaryawanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gajiKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idKaryawanInputPanel1.setBackground(new java.awt.Color(255, 221, 186));
        idKaryawanInputPanel1.setForeground(new java.awt.Color(255, 255, 255));

        idKaryawanInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idKaryawanInputLabel1.setForeground(new java.awt.Color(137, 92, 3));
        idKaryawanInputLabel1.setText("ID Karyawan");

        idKaryawanTextField.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout idKaryawanInputPanel1Layout = new javax.swing.GroupLayout(idKaryawanInputPanel1);
        idKaryawanInputPanel1.setLayout(idKaryawanInputPanel1Layout);
        idKaryawanInputPanel1Layout.setHorizontalGroup(
            idKaryawanInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKaryawanInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idKaryawanInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idKaryawanInputLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(idKaryawanTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idKaryawanInputPanel1Layout.setVerticalGroup(
            idKaryawanInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKaryawanInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idKaryawanInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idKaryawanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jabatanPanel.setBackground(new java.awt.Color(255, 221, 186));

        jabatanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jabatanLabel.setForeground(new java.awt.Color(137, 92, 3));
        jabatanLabel.setText("Jabatan");

        jabatanTextField.setBackground(new java.awt.Color(255, 255, 255));
        jabatanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jabatanPanelLayout = new javax.swing.GroupLayout(jabatanPanel);
        jabatanPanel.setLayout(jabatanPanelLayout);
        jabatanPanelLayout.setHorizontalGroup(
            jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jabatanLabel)
                    .addComponent(jabatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jabatanPanelLayout.setVerticalGroup(
            jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanPanelLayout.createSequentialGroup()
                .addComponent(jabatanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jabatanTextField)
                .addContainerGap())
        );

        javax.swing.GroupLayout karyawanFormPanelLayout = new javax.swing.GroupLayout(karyawanFormPanel);
        karyawanFormPanel.setLayout(karyawanFormPanelLayout);
        karyawanFormPanelLayout.setHorizontalGroup(
            karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addComponent(karyawanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gajiKaryawanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaKaryawanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idKaryawanInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jabatanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        karyawanFormPanelLayout.setVerticalGroup(
            karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(karyawanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(idKaryawanInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaKaryawanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gajiKaryawanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jabatanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147))
        );

        simpanJabatanButton.setBackground(new java.awt.Color(51, 151, 56));
        simpanJabatanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanJabatanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanJabatanButton.setText("Simpan");
        simpanJabatanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanJabatanButtonActionPerformed(evt);
            }
        });

        karyawanScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        karyawanTextArea.setBackground(new java.awt.Color(255, 255, 255));
        karyawanTextArea.setColumns(20);
        karyawanTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        karyawanTextArea.setRows(5);
        karyawanScrollPanel.setViewportView(karyawanTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKaryawanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(karyawanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanJabatanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(karyawanScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKaryawanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(karyawanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(simpanJabatanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(karyawanScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKaryawanInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKaryawanInputTextFieldKeyTyped
          if(evt.getKeyChar()=='\n'){
          if(searchKaryawanInputTextField.getText().isEmpty())
              return;
          
          Customer c = cc.searchCostumerByName(searchKaryawanInputTextField.getText());
          setEditDeleteButtonCustomer(true);
          clearTextCustomer();
          
          namaKaryawanInputTextField.setText(c.getNama());
          gajiKaryawanInputTextField.setText(c.getAlamat());
          alamatInputTextField.setText(c.getNo_telepon());
          
          idCustomer = c.getId_customer();
          }
    }//GEN-LAST:event_searchKaryawanInputTextFieldKeyTyped

    private void searchKaryawanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKaryawanInputButtonActionPerformed
          if(searchKaryawanInputTextField.getText().isEmpty())
              return;
          
          Customer c = cc.searchCostumerByName(searchKaryawanInputTextField.getText());
          setEditDeleteButtonCustomer(true);
          clearTextCustomer();
          
          namaKaryawanInputTextField.setText(c.getNama());
          gajiKaryawanInputTextField.setText(c.getAlamat());
          alamatInputTextField.setText(c.getNo_telepon());
          
          idCustomer = c.getId_customer();
    }//GEN-LAST:event_searchKaryawanInputButtonActionPerformed

    private void barukanKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKaryawanButtonActionPerformed
        actionCustomer = "update";
        setComponentsCustomer(true);
    }//GEN-LAST:event_barukanKaryawanButtonActionPerformed

    private void hapusKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKaryawanButtonActionPerformed
        actionCustomer = "delete";
        cc.deleteDataCustomer(idCustomer);
        idCustomer = 0;
        showCustomer();
    }//GEN-LAST:event_hapusKaryawanButtonActionPerformed

    private void tambahKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKaryawanButtonActionPerformed
        actionCustomer = "add";
        clearTextCustomer();
        setEditDeleteButtonCustomer(true);
        setComponentsCustomer(true);
    }//GEN-LAST:event_tambahKaryawanButtonActionPerformed

    private void namaKaryawanInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKaryawanInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKaryawanInputTextFieldActionPerformed

    private void simpanJabatanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanJabatanButtonActionPerformed
        // TODO add your handling code here:
        if(actionCustomer == null)
        return;
        try{
            inputKosongCustomerException();
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionCustomer + "?") == JOptionPane.CLOSED_OPTION)
            return;
            
            switch(actionCustomer){
                case "add":
                c = new Customer(namaKaryawanInputTextField.getText(),  alamatInputTextField.getText(),gajiKaryawanInputTextField.getText());
                cc.insertDataCustomer(c);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
                case "update":
                c = new Customer(namaKaryawanInputTextField.getText(), alamatInputTextField.getText() , gajiKaryawanInputTextField.getText());
                cc.updateDataCustomer(c, idCustomer);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
                default:
                break;
            }
            showCustomer();
            actionCustomer = null;
        }catch(InputKosongException e){
            System.out.println(e);
        };
    }//GEN-LAST:event_simpanJabatanButtonActionPerformed

    private void jabatanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanKaryawanButton;
    private javax.swing.JLabel gajiKaryawanInputLabel;
    private javax.swing.JPanel gajiKaryawanInputPanel;
    private javax.swing.JTextField gajiKaryawanInputTextField;
    private javax.swing.JButton hapusKaryawanButton;
    private javax.swing.JLabel idKaryawanInputLabel1;
    private javax.swing.JPanel idKaryawanInputPanel1;
    private javax.swing.JTextField idKaryawanTextField;
    private javax.swing.JLabel jabatanLabel;
    private javax.swing.JPanel jabatanPanel;
    private javax.swing.JTextField jabatanTextField;
    private javax.swing.JPanel karyawanButtonPanel;
    private javax.swing.JPanel karyawanFormPanel;
    private javax.swing.JScrollPane karyawanScrollPanel;
    private javax.swing.JTextArea karyawanTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaKaryawanInputLabel;
    private javax.swing.JTextField namaKaryawanInputTextField;
    private javax.swing.JPanel namaKaryawanPanel;
    private javax.swing.JButton searchKaryawanInputButton;
    private javax.swing.JLabel searchKaryawanInputLabel;
    private javax.swing.JPanel searchKaryawanInputPanel;
    private javax.swing.JTextField searchKaryawanInputTextField;
    private javax.swing.JButton simpanJabatanButton;
    private javax.swing.JButton tambahKaryawanButton;
    // End of variables declaration//GEN-END:variables
}
