/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.KendaraanControl;
import control.MobilControl;
import control.MotorControl;
import java.awt.Component;
import exception.InputKosongException;
import exception.InputSpecialAtributeException;
import javax.swing.JOptionPane;
import model.Kendaraan;
import model.Mobil;
import model.Motor;

public class menuMainPanel1 extends javax.swing.JPanel {
    private KendaraanControl kc = new KendaraanControl();
    private MotorControl mtrc = new MotorControl();
    private MobilControl mblc = new MobilControl();
    private Kendaraan k = null;
    private Mobil mbl = null;
    private Motor mtr = null;
    String actionKendaraan = null;

//    String action = null;
    private Component rootPane;
    
    public menuMainPanel1() {
        initComponents();
        setOpaque(false);
        showKendaraan();
        setComponentsKendaraan(false);
        setKendaraanEditDeleteButton(false);
        clearText();        
    }
    
    public void inputKosongKendaraanException() throws InputKosongException{
        if(namaMenuInputTextField.getText().isEmpty() || hargaMenuInputTextfield.getText().isEmpty())
            throw new InputKosongException();
    }

    private void InputSpecialAtributeKendaraanException() throws InputSpecialAtributeException{
        if(jenisInputButton.getText().equals("Motor") && !isInteger(specialAtributeInputTextfield.getText()))
            throw new InputSpecialAtributeException();
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void setComponentsKendaraan(boolean value){
        idMenuInputTextField.setEnabled(value);
        namaMenuInputTextField.setEnabled(value);
        hargaMenuInputTextfield.setEnabled(value);
        jenisInputButton.setEnabled(value);
    }
    
    public void setKendaraanEditDeleteButton(boolean value){
        barukanMenuButton.setEnabled(value);
        hapusMenuButton.setEnabled(value);
    }
    
    public void clearText(){
        idMenuInputTextField.setText("");
        namaMenuInputTextField.setText("");
        hargaMenuInputTextfield.setText("");
        jenisInputButton.setText("");
        searchPesananInputTextField.setText("");
        specialAtributeInputTextfield.setText("");
        specialAtributeInputLabel.setText("");
    }
    
    public void showKendaraan(){
        motorTextArea.setText("List Motor: \n ============= \n"+mtrc.showStringKendaraan());
        mobilTextArea.setText("List Mobil: \n ============= \n"+mblc.showStringKendaraan());
    }

    private boolean mobilIsSelected(){
        return jenisInputButton.getText().equals("Mobil");
    }
    
    private void doSearchKendaraan(){
        if(searchPesananInputTextField.getText().isEmpty())
            return;
        
            k = kc.searchDataKendaraan(searchPesananInputTextField.getText());
            
        if(k != null){
            setKendaraanEditDeleteButton(true);
            idMenuInputTextField.setText(k.getId_kendaraan());
            namaMenuInputTextField.setText(k.getNama());
            hargaMenuInputTextfield.setText(Float.toString(k.getHarga()));
            jenisInputButton.setText(k.getJenis());
            setSpecialAtributeLabel();
            specialAtributeInputTextfield.setText(k.getSpecial());
        }else{
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }

    private void setSpecialAtributeLabel(){
        if(jenisInputButton.getText().equals("Mobil")){
            specialAtributeInputLabel.setText("Jenis Mesin");
        }else{
            specialAtributeInputLabel.setText("Jumlah Tak");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchPesananInputPanel = new javax.swing.JPanel();
        searchPesananInputLabel = new javax.swing.JLabel();
        searchPesananInputTextField = new javax.swing.JTextField();
        searchPesananInputButton = new javax.swing.JButton();
        simpanKendaraanButton = new javax.swing.JButton();
        motorScrollPane = new javax.swing.JScrollPane();
        motorTextArea = new javax.swing.JTextArea();
        mobilScrollPane = new javax.swing.JScrollPane();
        mobilTextArea = new javax.swing.JTextArea();
        menuFormPanel = new javax.swing.JPanel();
        menuButtonPanel = new javax.swing.JPanel();
        barukanMenuButton = new javax.swing.JButton();
        hapusMenuButton = new javax.swing.JButton();
        tambahMenuButton = new javax.swing.JButton();
        idMenuInputPanel = new javax.swing.JPanel();
        idMenuInputLabel = new javax.swing.JLabel();
        idMenuInputTextField = new javax.swing.JTextField();
        namaMenuInputPanel = new javax.swing.JPanel();
        namaMenuInputLabel = new javax.swing.JLabel();
        namaMenuInputTextField = new javax.swing.JTextField();
        hargaMenuInputPanel = new javax.swing.JPanel();
        hargaMenunputLabel = new javax.swing.JLabel();
        hargaMenuInputTextfield = new javax.swing.JTextField();
        stokInputPanel = new javax.swing.JPanel();
        stokLabel = new javax.swing.JLabel();
        stokInputTextField = new javax.swing.JTextField();
        specialAtributeInputPanel = new javax.swing.JPanel();
        specialAtributeInputLabel = new javax.swing.JLabel();
        specialAtributeInputTextfield = new javax.swing.JTextField();
        jenisMenuInputPanel = new javax.swing.JPanel();
        jenisInputLabel = new javax.swing.JLabel();
        jenisInputButton = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 221, 186));

        mainPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchPesananInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchPesananInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPesananInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        searchPesananInputLabel.setText("Pencarian Pesanan");

        searchPesananInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        searchPesananInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPesananInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchPesananInputTextFieldKeyPressed(evt);
            }
        });

        searchPesananInputButton.setBackground(new java.awt.Color(137, 92, 3));
        searchPesananInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPesananInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPesananInputButton.setText("Cari");
        searchPesananInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPesananInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPesananInputPanelLayout = new javax.swing.GroupLayout(searchPesananInputPanel);
        searchPesananInputPanel.setLayout(searchPesananInputPanelLayout);
        searchPesananInputPanelLayout.setHorizontalGroup(
            searchPesananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPesananInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(searchPesananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPesananInputLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPesananInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPesananInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPesananInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        searchPesananInputPanelLayout.setVerticalGroup(
            searchPesananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPesananInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPesananInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPesananInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPesananInputTextField)
                    .addComponent(searchPesananInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanKendaraanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        motorScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        motorScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        motorTextArea.setBackground(new java.awt.Color(255, 255, 255));
        motorTextArea.setColumns(20);
        motorTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        motorTextArea.setRows(5);
        motorScrollPane.setViewportView(motorTextArea);

        mobilScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        mobilTextArea.setBackground(new java.awt.Color(255, 255, 255));
        mobilTextArea.setColumns(20);
        mobilTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        mobilTextArea.setRows(5);
        mobilTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mobilScrollPane.setViewportView(mobilTextArea);

        menuFormPanel.setBackground(new java.awt.Color(255, 221, 186));

        menuButtonPanel.setBackground(new java.awt.Color(255, 221, 186));

        barukanMenuButton.setBackground(new java.awt.Color(255, 175, 47));
        barukanMenuButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanMenuButton.setText("Barukan");
        barukanMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanMenuButtonActionPerformed(evt);
            }
        });

        hapusMenuButton.setBackground(new java.awt.Color(237, 78, 5));
        hapusMenuButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusMenuButton.setText("Hapus");
        hapusMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMenuButtonActionPerformed(evt);
            }
        });

        tambahMenuButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahMenuButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahMenuButton.setText("Tambah");
        tambahMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuButtonPanelLayout = new javax.swing.GroupLayout(menuButtonPanel);
        menuButtonPanel.setLayout(menuButtonPanelLayout);
        menuButtonPanelLayout.setHorizontalGroup(
            menuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahMenuButton)
                .addGap(18, 18, 18)
                .addComponent(barukanMenuButton)
                .addGap(18, 18, 18)
                .addComponent(hapusMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        menuButtonPanelLayout.setVerticalGroup(
            menuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idMenuInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        idMenuInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idMenuInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        idMenuInputLabel.setText("ID Menu");

        idMenuInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        idMenuInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idMenuInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMenuInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idMenuInputPanelLayout = new javax.swing.GroupLayout(idMenuInputPanel);
        idMenuInputPanel.setLayout(idMenuInputPanelLayout);
        idMenuInputPanelLayout.setHorizontalGroup(
            idMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idMenuInputTextField)
                    .addComponent(idMenuInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idMenuInputPanelLayout.setVerticalGroup(
            idMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idMenuInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idMenuInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaMenuInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        namaMenuInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaMenuInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        namaMenuInputLabel.setText("Nama Menu");

        namaMenuInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        namaMenuInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaMenuInputPanelLayout = new javax.swing.GroupLayout(namaMenuInputPanel);
        namaMenuInputPanel.setLayout(namaMenuInputPanelLayout);
        namaMenuInputPanelLayout.setHorizontalGroup(
            namaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaMenuInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaMenuInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaMenuInputPanelLayout.setVerticalGroup(
            namaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaMenuInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaMenuInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaMenuInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        hargaMenunputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaMenunputLabel.setForeground(new java.awt.Color(137, 92, 3));
        hargaMenunputLabel.setText("Harga");

        hargaMenuInputTextfield.setBackground(new java.awt.Color(255, 255, 255));
        hargaMenuInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaMenuInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaMenuInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout hargaMenuInputPanelLayout = new javax.swing.GroupLayout(hargaMenuInputPanel);
        hargaMenuInputPanel.setLayout(hargaMenuInputPanelLayout);
        hargaMenuInputPanelLayout.setHorizontalGroup(
            hargaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hargaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaMenuInputTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(hargaMenunputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hargaMenuInputPanelLayout.setVerticalGroup(
            hargaMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hargaMenunputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaMenuInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stokInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        stokLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        stokLabel.setForeground(new java.awt.Color(137, 92, 3));
        stokLabel.setText("Stok");

        stokInputTextField.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout stokInputPanelLayout = new javax.swing.GroupLayout(stokInputPanel);
        stokInputPanel.setLayout(stokInputPanelLayout);
        stokInputPanelLayout.setHorizontalGroup(
            stokInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stokLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(stokInputPanelLayout.createSequentialGroup()
                .addComponent(stokInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        stokInputPanelLayout.setVerticalGroup(
            stokInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stokLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stokInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuFormPanelLayout = new javax.swing.GroupLayout(menuFormPanel);
        menuFormPanel.setLayout(menuFormPanelLayout);
        menuFormPanelLayout.setHorizontalGroup(
            menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuFormPanelLayout.createSequentialGroup()
                        .addComponent(menuButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 311, Short.MAX_VALUE))
                    .addGroup(menuFormPanelLayout.createSequentialGroup()
                        .addGroup(menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaMenuInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idMenuInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaMenuInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(menuFormPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(stokInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        menuFormPanelLayout.setVerticalGroup(
            menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idMenuInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaMenuInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaMenuInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        specialAtributeInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        specialAtributeInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        specialAtributeInputLabel.setText("Deskripsi Makanan");

        specialAtributeInputTextfield.setBackground(new java.awt.Color(255, 255, 255));
        specialAtributeInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                specialAtributeInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout specialAtributeInputPanelLayout = new javax.swing.GroupLayout(specialAtributeInputPanel);
        specialAtributeInputPanel.setLayout(specialAtributeInputPanelLayout);
        specialAtributeInputPanelLayout.setHorizontalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(specialAtributeInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialAtributeInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        specialAtributeInputPanelLayout.setVerticalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specialAtributeInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(specialAtributeInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jenisMenuInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        jenisInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        jenisInputLabel.setText("Jenis");

        jenisInputButton.setBackground(new java.awt.Color(70, 39, 7));
        jenisInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisInputButton.setForeground(new java.awt.Color(255, 255, 255));
        jenisInputButton.setText("Makanan");
        jenisInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenisMenuInputPanelLayout = new javax.swing.GroupLayout(jenisMenuInputPanel);
        jenisMenuInputPanel.setLayout(jenisMenuInputPanelLayout);
        jenisMenuInputPanelLayout.setHorizontalGroup(
            jenisMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisMenuInputPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jenisMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisMenuInputPanelLayout.createSequentialGroup()
                        .addComponent(jenisInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jenisInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE))
                .addContainerGap())
        );
        jenisMenuInputPanelLayout.setVerticalGroup(
            jenisMenuInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisMenuInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPesananInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mobilScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(menuFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jenisMenuInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPesananInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                            .addComponent(jenisMenuInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(menuFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(motorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPesananInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPesananInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchPesananInputTextFieldKeyPressed

    private void searchPesananInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPesananInputButtonActionPerformed
        doSearchKendaraan();
    }//GEN-LAST:event_searchPesananInputButtonActionPerformed

    private void barukanMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanMenuButtonActionPerformed
        actionKendaraan = "update";
        setComponentsKendaraan(true);
        idMenuInputTextField.setEnabled(false);
    }//GEN-LAST:event_barukanMenuButtonActionPerformed

    private void hapusMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMenuButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION)
            return;
        
        kc.deleteDataKendaraan(idMenuInputTextField.getText());
        clearText();
        setKendaraanEditDeleteButton(false);
        setComponentsKendaraan(false);
        showKendaraan();
    }//GEN-LAST:event_hapusMenuButtonActionPerformed

    private void tambahMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMenuButtonActionPerformed
        actionKendaraan = "add";
        clearText();
        setKendaraanEditDeleteButton(false);
        setComponentsKendaraan(true);
        setKendaraanEditDeleteButton(false);
        
        idMenuInputTextField.setEnabled(false);
        idMenuInputTextField.setText(kc.generateId());
        jenisInputButton.setText("Mobil");
        setSpecialAtributeLabel();
    }//GEN-LAST:event_tambahMenuButtonActionPerformed

    private void idMenuInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMenuInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMenuInputTextFieldActionPerformed

    private void hargaMenuInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaMenuInputTextfieldKeyTyped

    }//GEN-LAST:event_hargaMenuInputTextfieldKeyTyped

    private void jenisInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisInputButtonActionPerformed
        switch(jenisInputButton.getText()){
            case "Mobil": jenisInputButton.setText("Motor"); break;
            case "Motor": jenisInputButton.setText("Mobil"); break;
        }
        setSpecialAtributeLabel();
    }//GEN-LAST:event_jenisInputButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        if(actionKendaraan == null)
            return;
        try{
            inputKosongKendaraanException();
            InputSpecialAtributeKendaraanException();
            
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionKendaraan + "?") == JOptionPane.CLOSED_OPTION)
                return;

            switch (actionKendaraan){
                case "add":
                    if(mobilIsSelected()){
                        mbl = new Mobil(specialAtributeInputTextfield.getText(), namaMenuInputTextField.getText(), 
                                jenisInputButton.getText(), Float.parseFloat(hargaMenuInputTextfield.getText()));
                        mblc.insertDataKendaraan(mbl);
                    }else{
                        mtr = new Motor(Integer.parseInt(specialAtributeInputTextfield.getText()), namaMenuInputTextField.getText(), 
                                jenisInputButton.getText(), Float.parseFloat(hargaMenuInputTextfield.getText()));
                        mtrc.insertDataKendaraan(mtr);
                    }
                    clearText();
                    setKendaraanEditDeleteButton(false);
                    setComponentsKendaraan(false);
                    showKendaraan();
                    break;
                case "update":
                    if(mobilIsSelected()){
                        mbl = new Mobil(specialAtributeInputTextfield.getText(),idMenuInputTextField.getText(), namaMenuInputTextField.getText(), 
                                jenisInputButton.getText(), Float.parseFloat(hargaMenuInputTextfield.getText()));
                        mblc.updateDataKendaraan(mbl);
                    }else{
                        mtr = new Motor(Integer.parseInt(specialAtributeInputTextfield.getText()),idMenuInputTextField.getText(), namaMenuInputTextField.getText(), 
                                jenisInputButton.getText(), Float.parseFloat(hargaMenuInputTextfield.getText()));
                        mtrc.updateDataKendaraan(mtr);
                    }
                    clearText();
                    setKendaraanEditDeleteButton(false);
                    setComponentsKendaraan(false);
                    showKendaraan();
                    break;
                default:
                    break;
            }
            actionKendaraan = null;
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(InputSpecialAtributeException e){
            JOptionPane.showMessageDialog(rootPane, e.message(jenisInputButton.getText()));
        }
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void specialAtributeInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specialAtributeInputTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_specialAtributeInputTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanMenuButton;
    private javax.swing.JButton hapusMenuButton;
    private javax.swing.JPanel hargaMenuInputPanel;
    private javax.swing.JTextField hargaMenuInputTextfield;
    private javax.swing.JLabel hargaMenunputLabel;
    private javax.swing.JLabel idMenuInputLabel;
    private javax.swing.JPanel idMenuInputPanel;
    private javax.swing.JTextField idMenuInputTextField;
    private javax.swing.JButton jenisInputButton;
    private javax.swing.JLabel jenisInputLabel;
    private javax.swing.JPanel jenisMenuInputPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuButtonPanel;
    private javax.swing.JPanel menuFormPanel;
    private javax.swing.JScrollPane mobilScrollPane;
    private javax.swing.JTextArea mobilTextArea;
    private javax.swing.JScrollPane motorScrollPane;
    private javax.swing.JTextArea motorTextArea;
    private javax.swing.JLabel namaMenuInputLabel;
    private javax.swing.JPanel namaMenuInputPanel;
    private javax.swing.JTextField namaMenuInputTextField;
    private javax.swing.JButton searchPesananInputButton;
    private javax.swing.JLabel searchPesananInputLabel;
    private javax.swing.JPanel searchPesananInputPanel;
    private javax.swing.JTextField searchPesananInputTextField;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JLabel specialAtributeInputLabel;
    private javax.swing.JPanel specialAtributeInputPanel;
    private javax.swing.JTextField specialAtributeInputTextfield;
    private javax.swing.JPanel stokInputPanel;
    private javax.swing.JTextField stokInputTextField;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JButton tambahMenuButton;
    // End of variables declaration//GEN-END:variables
}
