/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;


import java.awt.Component;
import javax.swing.JOptionPane;


public class pelangganMainPanel1 extends javax.swing.JPanel {

    String actionCustomer = null;
    int idCustomer = 0;
    private Component rootPane;
    
    public pelangganMainPanel1() {
        initComponents();
        setOpaque(false);
        showCustomer();
        setComponentsCustomer(false);        
        setEditDeleteButtonCustomer(false);        
        clearTextCustomer();
    }
    
    // Customer Set Komponen
    public void setComponentsCustomer(boolean value){
        idPelangganInputTextField.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }
    
    // Customer Set Edit Delete Button
    public void setEditDeleteButtonCustomer(boolean value){
        barukanKaryawanButton.setEnabled(value);
        hapusKaryawanButton.setEnabled(value);
    }
    
    // Customer Clear Text
    public void clearTextCustomer(){
        idPelangganInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        alamatInputTextField.setText("");
        searchKaryawanInputTextField.setText("");
    }
    
    public void showCustomer(){
        karyawanTextArea.setText("List Customer: \n ============= \n"+cc.showAllStringCustomer());
    }

    public void inputKosongCustomerException() throws InputKosongException{
        if(idPelangganInputTextField.getText().isEmpty() || alamatInputTextField.getText().isEmpty() || nomorTeleponInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKaryawanInputPanel = new javax.swing.JPanel();
        searchKaryawanInputLabel = new javax.swing.JLabel();
        searchKaryawanInputTextField = new javax.swing.JTextField();
        searchKaryawanInputButton = new javax.swing.JButton();
        karyawanFormPanel = new javax.swing.JPanel();
        karyawanButtonPanel = new javax.swing.JPanel();
        barukanKaryawanButton = new javax.swing.JButton();
        hapusKaryawanButton = new javax.swing.JButton();
        tambahKaryawanButton = new javax.swing.JButton();
        idPelangganPanel = new javax.swing.JPanel();
        idPelangganInputLabel = new javax.swing.JLabel();
        idPelangganInputTextField = new javax.swing.JTextField();
        namaPelangganInputPanel1 = new javax.swing.JPanel();
        namaPelangganInputLabel1 = new javax.swing.JLabel();
        namaPelangganTextField = new javax.swing.JTextField();
        AlamatPanel = new javax.swing.JPanel();
        AlamatLabel = new javax.swing.JLabel();
        AlamatsScrolarea = new javax.swing.JScrollPane();
        AlamatTextField = new javax.swing.JTextArea();
        NomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        simpanPelangganButton = new javax.swing.JButton();
        karyawanScrollPanel = new javax.swing.JScrollPane();
        karyawanTextArea = new javax.swing.JTextArea();

        setForeground(new java.awt.Color(255, 218, 182));

        mainPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchKaryawanInputPanel.setBackground(new java.awt.Color(255, 221, 186));

        searchKaryawanInputLabel.setBackground(new java.awt.Color(51, 151, 56));
        searchKaryawanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputLabel.setText("Pencarian Pelanggan");

        searchKaryawanInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        searchKaryawanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKaryawanInputTextFieldKeyTyped(evt);
            }
        });

        searchKaryawanInputButton.setBackground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKaryawanInputButton.setText("Cari");
        searchKaryawanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKaryawanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchKaryawanInputPanelLayout = new javax.swing.GroupLayout(searchKaryawanInputPanel);
        searchKaryawanInputPanel.setLayout(searchKaryawanInputPanelLayout);
        searchKaryawanInputPanelLayout.setHorizontalGroup(
            searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKaryawanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                        .addComponent(searchKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 516, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchKaryawanInputPanelLayout.setVerticalGroup(
            searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKaryawanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKaryawanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKaryawanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchKaryawanInputTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        karyawanFormPanel.setBackground(new java.awt.Color(255, 221, 186));
        karyawanFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        karyawanButtonPanel.setBackground(new java.awt.Color(255, 221, 186));

        barukanKaryawanButton.setBackground(new java.awt.Color(255, 175, 47));
        barukanKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKaryawanButton.setText("Barukan");
        barukanKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKaryawanButtonActionPerformed(evt);
            }
        });

        hapusKaryawanButton.setBackground(new java.awt.Color(237, 78, 5));
        hapusKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKaryawanButton.setText("Hapus");
        hapusKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKaryawanButtonActionPerformed(evt);
            }
        });

        tambahKaryawanButton.setBackground(new java.awt.Color(51, 151, 56));
        tambahKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKaryawanButton.setText("Tambah");
        tambahKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKaryawanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout karyawanButtonPanelLayout = new javax.swing.GroupLayout(karyawanButtonPanel);
        karyawanButtonPanel.setLayout(karyawanButtonPanelLayout);
        karyawanButtonPanelLayout.setHorizontalGroup(
            karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        karyawanButtonPanelLayout.setVerticalGroup(
            karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(karyawanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPelangganPanel.setBackground(new java.awt.Color(255, 221, 186));
        idPelangganPanel.setForeground(new java.awt.Color(255, 255, 255));

        idPelangganInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        idPelangganInputLabel.setText("ID Pelanggan");

        idPelangganInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        idPelangganInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPelangganPanelLayout = new javax.swing.GroupLayout(idPelangganPanel);
        idPelangganPanel.setLayout(idPelangganPanelLayout);
        idPelangganPanelLayout.setHorizontalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPelangganInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPelangganPanelLayout.setVerticalGroup(
            idPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPelangganInputPanel1.setBackground(new java.awt.Color(255, 221, 186));
        namaPelangganInputPanel1.setForeground(new java.awt.Color(255, 255, 255));

        namaPelangganInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPelangganInputLabel1.setForeground(new java.awt.Color(137, 92, 3));
        namaPelangganInputLabel1.setText("Nama Pelanggan");

        namaPelangganTextField.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout namaPelangganInputPanel1Layout = new javax.swing.GroupLayout(namaPelangganInputPanel1);
        namaPelangganInputPanel1.setLayout(namaPelangganInputPanel1Layout);
        namaPelangganInputPanel1Layout.setHorizontalGroup(
            namaPelangganInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPelangganInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaPelangganInputLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaPelangganTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPelangganInputPanel1Layout.setVerticalGroup(
            namaPelangganInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPelangganInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelangganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        AlamatPanel.setBackground(new java.awt.Color(255, 221, 186));

        AlamatLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        AlamatLabel.setForeground(new java.awt.Color(137, 92, 3));
        AlamatLabel.setText("Alamat");

        AlamatTextField.setBackground(new java.awt.Color(255, 255, 255));
        AlamatTextField.setColumns(20);
        AlamatTextField.setRows(5);
        AlamatsScrolarea.setViewportView(AlamatTextField);

        javax.swing.GroupLayout AlamatPanelLayout = new javax.swing.GroupLayout(AlamatPanel);
        AlamatPanel.setLayout(AlamatPanelLayout);
        AlamatPanelLayout.setHorizontalGroup(
            AlamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlamatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlamatLabel)
                    .addComponent(AlamatsScrolarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        AlamatPanelLayout.setVerticalGroup(
            AlamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlamatPanelLayout.createSequentialGroup()
                .addComponent(AlamatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlamatsScrolarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NomorTeleponInputPanel.setBackground(new java.awt.Color(255, 221, 186));
        NomorTeleponInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout NomorTeleponInputPanelLayout = new javax.swing.GroupLayout(NomorTeleponInputPanel);
        NomorTeleponInputPanel.setLayout(NomorTeleponInputPanelLayout);
        NomorTeleponInputPanelLayout.setHorizontalGroup(
            NomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        NomorTeleponInputPanelLayout.setVerticalGroup(
            NomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NomorTeleponInputPanelLayout.createSequentialGroup()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        simpanPelangganButton.setBackground(new java.awt.Color(51, 151, 56));
        simpanPelangganButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout karyawanFormPanelLayout = new javax.swing.GroupLayout(karyawanFormPanel);
        karyawanFormPanel.setLayout(karyawanFormPanelLayout);
        karyawanFormPanelLayout.setHorizontalGroup(
            karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                                .addComponent(karyawanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaPelangganInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanFormPanelLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanFormPanelLayout.createSequentialGroup()
                                .addComponent(simpanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, karyawanFormPanelLayout.createSequentialGroup()
                                .addComponent(AlamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))))))
        );
        karyawanFormPanelLayout.setVerticalGroup(
            karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(karyawanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(namaPelangganInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(karyawanFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(karyawanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(simpanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        karyawanScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        karyawanTextArea.setBackground(new java.awt.Color(255, 255, 255));
        karyawanTextArea.setColumns(20);
        karyawanTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        karyawanTextArea.setRows(5);
        karyawanScrollPanel.setViewportView(karyawanTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKaryawanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(karyawanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 495, Short.MAX_VALUE))
                    .addComponent(karyawanScrollPanel))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKaryawanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(karyawanScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKaryawanInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKaryawanInputTextFieldKeyTyped
          if(evt.getKeyChar()=='\n'){
          if(searchKaryawanInputTextField.getText().isEmpty())
              return;
          
          Customer c = cc.searchCostumerByName(searchKaryawanInputTextField.getText());
          setEditDeleteButtonCustomer(true);
          clearTextCustomer();
          
          idPelangganInputTextField.setText(c.getNama());
          nomorTeleponInputTextField.setText(c.getAlamat());
          alamatInputTextField.setText(c.getNo_telepon());
          
          idCustomer = c.getId_customer();
          }
    }//GEN-LAST:event_searchKaryawanInputTextFieldKeyTyped

    private void searchKaryawanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKaryawanInputButtonActionPerformed
          if(searchKaryawanInputTextField.getText().isEmpty())
              return;
          
          Customer c = cc.searchCostumerByName(searchKaryawanInputTextField.getText());
          setEditDeleteButtonCustomer(true);
          clearTextCustomer();
          
          idPelangganInputTextField.setText(c.getNama());
          nomorTeleponInputTextField.setText(c.getAlamat());
          alamatInputTextField.setText(c.getNo_telepon());
          
          idCustomer = c.getId_customer();
    }//GEN-LAST:event_searchKaryawanInputButtonActionPerformed

    private void barukanKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKaryawanButtonActionPerformed
        actionCustomer = "update";
        setComponentsCustomer(true);
    }//GEN-LAST:event_barukanKaryawanButtonActionPerformed

    private void hapusKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKaryawanButtonActionPerformed
        actionCustomer = "delete";
        cc.deleteDataCustomer(idCustomer);
        idCustomer = 0;
        showCustomer();
    }//GEN-LAST:event_hapusKaryawanButtonActionPerformed

    private void tambahKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKaryawanButtonActionPerformed
        actionCustomer = "add";
        clearTextCustomer();
        setEditDeleteButtonCustomer(true);
        setComponentsCustomer(true);
    }//GEN-LAST:event_tambahKaryawanButtonActionPerformed

    private void idPelangganInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganInputTextFieldActionPerformed

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        // TODO add your handling code here:
        if(actionCustomer == null)
        return;
        try{
            inputKosongCustomerException();
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionCustomer + "?") == JOptionPane.CLOSED_OPTION)
            return;
            
            switch(actionCustomer){
                case "add":
                c = new Customer(idPelangganInputTextField.getText(),  alamatInputTextField.getText(),nomorTeleponInputTextField.getText());
                cc.insertDataCustomer(c);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
                case "update":
                c = new Customer(idPelangganInputTextField.getText(), alamatInputTextField.getText() , nomorTeleponInputTextField.getText());
                cc.updateDataCustomer(c, idCustomer);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
                default:
                break;
            }
            showCustomer();
            actionCustomer = null;
        }catch(InputKosongException e){
            System.out.println(e);
        };
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatLabel;
    private javax.swing.JPanel AlamatPanel;
    private javax.swing.JTextArea AlamatTextField;
    private javax.swing.JScrollPane AlamatsScrolarea;
    private javax.swing.JPanel NomorTeleponInputPanel;
    private javax.swing.JButton barukanKaryawanButton;
    private javax.swing.JButton hapusKaryawanButton;
    private javax.swing.JLabel idPelangganInputLabel;
    private javax.swing.JTextField idPelangganInputTextField;
    private javax.swing.JPanel idPelangganPanel;
    private javax.swing.JPanel karyawanButtonPanel;
    private javax.swing.JPanel karyawanFormPanel;
    private javax.swing.JScrollPane karyawanScrollPanel;
    private javax.swing.JTextArea karyawanTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaPelangganInputLabel1;
    private javax.swing.JPanel namaPelangganInputPanel1;
    private javax.swing.JTextField namaPelangganTextField;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JButton searchKaryawanInputButton;
    private javax.swing.JLabel searchKaryawanInputLabel;
    private javax.swing.JPanel searchKaryawanInputPanel;
    private javax.swing.JTextField searchKaryawanInputTextField;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JButton tambahKaryawanButton;
    // End of variables declaration//GEN-END:variables
}
