package panelView;

import control.KaryawanControl;
import control.PelangganControl;
import java.awt.Component;
import exception.InputKosongException;
import exception.InputHarusAngkaException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Karyawan;
import model.Pelanggan;

public class PelangganMainPanel extends javax.swing.JPanel {

    private PelangganControl pc = new PelangganControl();
    private Pelanggan p = null;
    String actionPelanggan = null;

    private Component rootPane;
    private String selectedId = "";

    public PelangganMainPanel() {
        initComponents();
        setOpaque(false);
        showPelanggan();
        setComponentsPelanggan(false);
        idPelangganInputTextField.setEnabled(false); // langsung false saja karena rencananya id gak bisa di ubah
        setPelangganEditDeleteButton(false);
        clearText();
    }

    public void inputKosongPelangganException() throws InputKosongException {
        if (idPelangganInputTextField.getText().isEmpty() || namaPelangganInputTextfield.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }

    private void InputHarusAngkaPelangganException() throws InputHarusAngkaException { // exception khusus untuk gaji
        if (!isFloat(nomorTeleponInputTextField.getText())) {
            throw new InputHarusAngkaException();
        }
    }
    
    private boolean isFloat(String input) {
        try {
            Float.parseFloat(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    public void setComponentsPelanggan(boolean value) { // ngeset tempat input
        idPelangganInputTextField.setEnabled(value);
        namaPelangganInputTextfield.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }

    public void setPelangganEditDeleteButton(boolean value) { // membuka/tutup tombol barukan dan hapus jika mau/tidak mau ngedit data
        barukanKaryawanButton.setEnabled(value);
        hapusKaryawanButton.setEnabled(value);
    }

    public void clearText() {
        idPelangganInputTextField.setText("");
        namaPelangganInputTextfield.setText("");
        searchKaryawanInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        alamatInputTextField.setText("");
        idPelangganInputTextField.setText("");
    }
    
    public void showPelanggan(){
        tabelPelanggan.setModel(pc.showTable(""));
        addHeaderClickListener(tabelPelanggan);
    }

    private void doSearchKaryawan() { // fungsi untuk search dipakai di : searchKaryawanInputButtonActionPerformed
        if (searchKaryawanInputTextField.getText().isEmpty()) {
            return;
        }

        p = pc.searchDataPelanggan(searchKaryawanInputTextField.getText()); // mencari berdasarkan ID

        if (p != null) { // jika ketemu datanya
            tabelPelanggan.setModel(pc.showTable(searchKaryawanInputTextField.getText()));
//            setKaryawanEditDeleteButton(true); // maka tombol edit dan delete dibuka
//            namaKaryawanInputTextField.setText(k.getNama_karyawan()); // // mencopy data yang ditemukan di field input
//            gajiKaryawanInputTextfield.setText(Float.toString(k.getGaji()));
//            usernameKaryawanInputTextField.setText(k.getUsername());
//            passwordKaryawanInputTextField.setText(k.getPassword());
//            jabatanInputButton.setText(k.getJabatan());
//            idKaryawanInputTextField.setText(k.getId_karyawan());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }

    private static void addHeaderClickListener(JTable table) {
        JTableHeader header = table.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int col = header.columnAtPoint(e.getPoint());
            }
        });
        TableModel tableModel = table.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>((TableModel) tableModel);
        table.setRowSorter(sorter);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainPanel = new javax.swing.JPanel();
        searchKendaraanInputPanel = new javax.swing.JPanel();
        searchKaryawanInputLabel = new javax.swing.JLabel();
        searchKaryawanInputTextField = new javax.swing.JTextField();
        searchKaryawanInputButton = new javax.swing.JButton();
        kendaraanFormPanel = new javax.swing.JPanel();
        KendaraanButtonPanel = new javax.swing.JPanel();
        barukanKaryawanButton = new javax.swing.JButton();
        hapusKaryawanButton = new javax.swing.JButton();
        tambahKaryawanButton = new javax.swing.JButton();
        idPelangganInputPanel = new javax.swing.JPanel();
        idPelangganInputLabel = new javax.swing.JLabel();
        idPelangganInputTextField = new javax.swing.JTextField();
        nomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        namaPelangganInputPanel = new javax.swing.JPanel();
        namaPelangganInputLabel = new javax.swing.JLabel();
        namaPelangganInputTextfield = new javax.swing.JTextField();
        alamatInputPanel = new javax.swing.JPanel();
        alamatInputTextField = new javax.swing.JTextField();
        alamatInputLabel = new javax.swing.JLabel();
        specialAtributeInputPanel = new javax.swing.JPanel();
        simpanKaryawanButton = new javax.swing.JButton();
        batalkanKaryawanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 218, 182));

        mainPanel.setBackground(new java.awt.Color(255, 218, 182));

        searchKendaraanInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        searchKaryawanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputLabel.setText("Pencarian Karyawan");

        searchKaryawanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKaryawanInputTextFieldKeyPressed(evt);
            }
        });

        searchKaryawanInputButton.setBackground(new java.awt.Color(137, 92, 3));
        searchKaryawanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKaryawanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKaryawanInputButton.setText("Cari");
        searchKaryawanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKaryawanInputButtonActionPerformed(evt);
            }
        });

        kendaraanFormPanel.setBackground(new java.awt.Color(255, 218, 182));

        KendaraanButtonPanel.setBackground(new java.awt.Color(255, 218, 182));

        barukanKaryawanButton.setBackground(new java.awt.Color(255, 175, 47));
        barukanKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKaryawanButton.setText("Barukan");
        barukanKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKaryawanButtonActionPerformed(evt);
            }
        });

        hapusKaryawanButton.setBackground(new java.awt.Color(237, 78, 5));
        hapusKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKaryawanButton.setText("Hapus");
        hapusKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKaryawanButtonActionPerformed(evt);
            }
        });

        tambahKaryawanButton.setBackground(new java.awt.Color(51, 151, 56));
        tambahKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKaryawanButton.setText("Tambah");
        tambahKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKaryawanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KendaraanButtonPanelLayout = new javax.swing.GroupLayout(KendaraanButtonPanel);
        KendaraanButtonPanel.setLayout(KendaraanButtonPanelLayout);
        KendaraanButtonPanelLayout.setHorizontalGroup(
            KendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KendaraanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKaryawanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        KendaraanButtonPanelLayout.setVerticalGroup(
            KendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KendaraanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKaryawanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPelangganInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        idPelangganInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        idPelangganInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPelangganInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        idPelangganInputLabel.setText("ID Pelanggan");

        idPelangganInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout idPelangganInputPanelLayout = new javax.swing.GroupLayout(idPelangganInputPanel);
        idPelangganInputPanel.setLayout(idPelangganInputPanelLayout);
        idPelangganInputPanelLayout.setHorizontalGroup(
            idPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelangganInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(idPelangganInputPanelLayout.createSequentialGroup()
                        .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        idPelangganInputPanelLayout.setVerticalGroup(
            idPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nomorTeleponInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        nomorTeleponInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorTeleponInputPanelLayout = new javax.swing.GroupLayout(nomorTeleponInputPanel);
        nomorTeleponInputPanel.setLayout(nomorTeleponInputPanelLayout);
        nomorTeleponInputPanelLayout.setHorizontalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                        .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nomorTeleponInputPanelLayout.setVerticalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        namaPelangganInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        namaPelangganInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPelangganInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        namaPelangganInputLabel.setText("Nama");

        namaPelangganInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPelangganInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaPelangganInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout namaPelangganInputPanelLayout = new javax.swing.GroupLayout(namaPelangganInputPanel);
        namaPelangganInputPanel.setLayout(namaPelangganInputPanelLayout);
        namaPelangganInputPanelLayout.setHorizontalGroup(
            namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanelLayout.createSequentialGroup()
                .addGroup(namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namaPelangganInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namaPelangganInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(namaPelangganInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        namaPelangganInputPanelLayout.setVerticalGroup(
            namaPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(namaPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelangganInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        alamatInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        alamatInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        alamatInputLabel.setBackground(new java.awt.Color(0, 0, 0));
        alamatInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel.setForeground(new java.awt.Color(137, 92, 3));
        alamatInputLabel.setText("Alamat");

        javax.swing.GroupLayout alamatInputPanelLayout = new javax.swing.GroupLayout(alamatInputPanel);
        alamatInputPanel.setLayout(alamatInputPanelLayout);
        alamatInputPanelLayout.setHorizontalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addComponent(alamatInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        alamatInputPanelLayout.setVerticalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatInputPanelLayout.createSequentialGroup()
                .addComponent(alamatInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout kendaraanFormPanelLayout = new javax.swing.GroupLayout(kendaraanFormPanel);
        kendaraanFormPanel.setLayout(kendaraanFormPanelLayout);
        kendaraanFormPanelLayout.setHorizontalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addComponent(KendaraanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 350, Short.MAX_VALUE))
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPelangganInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPelangganInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                                .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        kendaraanFormPanelLayout.setVerticalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KendaraanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idPelangganInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPelangganInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        specialAtributeInputPanel.setBackground(new java.awt.Color(255, 218, 182));

        javax.swing.GroupLayout specialAtributeInputPanelLayout = new javax.swing.GroupLayout(specialAtributeInputPanel);
        specialAtributeInputPanel.setLayout(specialAtributeInputPanelLayout);
        specialAtributeInputPanelLayout.setHorizontalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        specialAtributeInputPanelLayout.setVerticalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        simpanKaryawanButton.setBackground(new java.awt.Color(51, 151, 56));
        simpanKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKaryawanButton.setText("Simpan");
        simpanKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKaryawanButtonActionPerformed(evt);
            }
        });

        batalkanKaryawanButton.setBackground(new java.awt.Color(237, 78, 5));
        batalkanKaryawanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalkanKaryawanButton.setForeground(new java.awt.Color(255, 255, 255));
        batalkanKaryawanButton.setText("Batalkan");
        batalkanKaryawanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalkanKaryawanButtonMouseClicked(evt);
            }
        });
        batalkanKaryawanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanKaryawanButtonActionPerformed(evt);
            }
        });

        tabelPelanggan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout searchKendaraanInputPanelLayout = new javax.swing.GroupLayout(searchKendaraanInputPanel);
        searchKendaraanInputPanel.setLayout(searchKendaraanInputPanelLayout);
        searchKendaraanInputPanelLayout.setHorizontalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchKaryawanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                                .addComponent(searchKaryawanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 531, Short.MAX_VALUE))))
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(batalkanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        searchKendaraanInputPanelLayout.setVerticalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKaryawanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchKaryawanInputTextField)
                    .addComponent(searchKaryawanInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batalkanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanKaryawanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKaryawanInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKaryawanInputTextFieldKeyPressed

    }//GEN-LAST:event_searchKaryawanInputTextFieldKeyPressed

    private void searchKaryawanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKaryawanInputButtonActionPerformed
        doSearchKaryawan();
    }//GEN-LAST:event_searchKaryawanInputButtonActionPerformed

    private void barukanKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKaryawanButtonActionPerformed
        actionPelanggan = "update"; 
        setComponentsPelanggan(true); // membuka akses field input
    }//GEN-LAST:event_barukanKaryawanButtonActionPerformed

    private void hapusKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKaryawanButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
            return;
        }

        pc.deleteDataPelanggan(idPelangganInputTextField.getText()); // delete berdasarkan id
        clearText(); // bersihin field input
        setPelangganEditDeleteButton(false); 
        setComponentsPelanggan(false); // tutup field input
        showPelanggan(); // melakukan show ulang
    }//GEN-LAST:event_hapusKaryawanButtonActionPerformed

    private void tambahKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKaryawanButtonActionPerformed
        actionPelanggan = "add";
        clearText(); // bersihin field input
        setPelangganEditDeleteButton(false); // membatasi tombol edit dan hapus
        setComponentsPelanggan(true); // membuka field input

        idPelangganInputTextField.setEnabled(false); // mastikan saja biar tidak dibuka 
        idPelangganInputTextField.setText(pc.generateId()); // membuat ID baru berdasarkan nilai id tertinggi
    }//GEN-LAST:event_tambahKaryawanButtonActionPerformed

    private void simpanKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKaryawanButtonActionPerformed
        if (actionPelanggan == null) {
            return;
        }
        try {
            inputKosongPelangganException();
            InputHarusAngkaPelangganException();

            if (JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionPelanggan + "?") == JOptionPane.CLOSED_OPTION) {
                return;
            }

            switch (actionPelanggan) {
                case "add":
                    p = new Pelanggan (idPelangganInputTextField.getText(), namaPelangganInputTextfield.getText(), alamatInputTextField.getText(),nomorTeleponInputTextField.getText());
                    pc.insertDataPelanggan(p);
                    clearText();
                    setPelangganEditDeleteButton(false);
                    setComponentsPelanggan(false);
                    showPelanggan();
                    break;
                case "update":
                    p = new Pelanggan (namaPelangganInputTextfield.getText(),alamatInputTextField.getText(),nomorTeleponInputTextField.getText());
                    pc.updateDataPelanggan(p);
                    clearText();
                    setPelangganEditDeleteButton(false);
                    setComponentsPelanggan(false);
                    showPelanggan();
                    break;
                default:
                    break;
            }
            actionPelanggan = null;
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(rootPane, e.message());
        } catch (InputHarusAngkaException e2) {
            JOptionPane.showMessageDialog(rootPane, e2.message());
        }
    }//GEN-LAST:event_simpanKaryawanButtonActionPerformed

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        actionPelanggan = "baharui";
        
        tambahKaryawanButton.setEnabled(false);
        batalkanKaryawanButton.setEnabled(true);
        simpanKaryawanButton.setEnabled(true);        
        setPelangganEditDeleteButton(true);
        
        setComponentsPelanggan(false);
        
        int clickedRow = tabelPelanggan.getSelectedRow();
        TableModel tableModel = tabelPelanggan.getModel();
        if (tabelPelanggan.getRowSorter() != null) {
            clickedRow = tabelPelanggan.convertRowIndexToModel(clickedRow);
        }
        selectedId = tableModel.getValueAt(clickedRow, 0).toString();

        idPelangganInputTextField.setText(tableModel.getValueAt(clickedRow, 0).toString()); 
        namaPelangganInputTextfield.setText(tableModel.getValueAt(clickedRow, 1).toString());
        alamatInputTextField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        nomorTeleponInputTextField.setText(tableModel.getValueAt(clickedRow, 3).toString());
        
        batalkanKaryawanButton.setEnabled(true);
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void batalkanKaryawanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanKaryawanButtonActionPerformed
        clearText();
        showPelanggan();
        setPelangganEditDeleteButton(false);
        setComponentsPelanggan(false);
        tambahKaryawanButton.setEnabled(true);
        tabelPelanggan.clearSelection();
        
    }//GEN-LAST:event_batalkanKaryawanButtonActionPerformed

    private void batalkanKaryawanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalkanKaryawanButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_batalkanKaryawanButtonMouseClicked

    private void namaPelangganInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPelangganInputTextfieldKeyTyped

    }//GEN-LAST:event_namaPelangganInputTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KendaraanButtonPanel;
    private javax.swing.JLabel alamatInputLabel;
    private javax.swing.JPanel alamatInputPanel;
    private javax.swing.JTextField alamatInputTextField;
    private javax.swing.JButton barukanKaryawanButton;
    private javax.swing.JButton batalkanKaryawanButton;
    private javax.swing.JButton hapusKaryawanButton;
    private javax.swing.JLabel idPelangganInputLabel;
    private javax.swing.JPanel idPelangganInputPanel;
    private javax.swing.JTextField idPelangganInputTextField;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kendaraanFormPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaPelangganInputLabel;
    private javax.swing.JPanel namaPelangganInputPanel;
    private javax.swing.JTextField namaPelangganInputTextfield;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JPanel nomorTeleponInputPanel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JButton searchKaryawanInputButton;
    private javax.swing.JLabel searchKaryawanInputLabel;
    private javax.swing.JTextField searchKaryawanInputTextField;
    private javax.swing.JPanel searchKendaraanInputPanel;
    private javax.swing.JButton simpanKaryawanButton;
    private javax.swing.JPanel specialAtributeInputPanel;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JButton tambahKaryawanButton;
    // End of variables declaration//GEN-END:variables
}
