/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.PenitipControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.Karyawan;

public class PenitipMainPanel extends javax.swing.JPanel {
    private PenitipControl dataControl = new PenitipControl();
    private Karyawan dataModel = null;


    String actionCustomer = null;
    int idCustomer = 0;
    private Component rootPane;
    
   
   
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public PenitipMainPanel() {
        initComponents();
        showCustomer();
        setComponentsData(false);
        
        setEditDeleteButtonData(false);
        
        clearTextData();
    }
    
    // Customer Set Komponen
    private void setComponentsData(boolean value){
        namaPenitipInputTextField.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }
   
    // Customer Set Edit Delete Button
    private void setEditDeleteButtonData(boolean value){
        barukanPenitipButton.setEnabled(value);
        hapusPenitipButton.setEnabled(value);
    }
    
    // Customer Clear Text
    private void clearTextData(){
        namaPenitipInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        alamatInputTextField.setText("");
        searchPenitipInputTextField.setText("");
    }
    
    private void showCustomer(){
        penitipTextArea.setText("List Penitip: \n ============= \n"+dataControl.showAllStringPenitip());
    }
    
    private void doSearchCustomer(){
        if(searchPenitipInputTextField.getText().isEmpty())
            return;
            Karyawan c = dataControl.searchCustomerById(Integer.parseInt(searchPenitipInputTextField.getText()));
            if(c == null ){
                JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
                return;
            }
            
            setEditDeleteButtonData(true);
            clearTextData();
            
            namaPenitipInputTextField.setText(c.getNama());
            nomorTeleponInputTextField.setText(c.getAlamat());
            alamatInputTextField.setText(c.getNo_telepon());
            
            idCustomer = c.getId_penitip();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        searchPenitipInputPanel = new javax.swing.JPanel();
        searchPenitipInputLabel = new javax.swing.JLabel();
        searchPenitipInputTextField = new javax.swing.JTextField();
        searchPenitipInputButton = new javax.swing.JButton();
        penitipFormPanel = new javax.swing.JPanel();
        penitipButtonPanel = new javax.swing.JPanel();
        barukanPenitipButton = new javax.swing.JButton();
        hapusPenitipButton = new javax.swing.JButton();
        tambahPenitipButton = new javax.swing.JButton();
        namaPenitipPanel = new javax.swing.JPanel();
        namaPenitipInputLabel = new javax.swing.JLabel();
        namaPenitipInputTextField = new javax.swing.JTextField();
        nomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        alamatInputPanel = new javax.swing.JPanel();
        alamatInputLabel = new javax.swing.JLabel();
        alamatScrollPane = new javax.swing.JScrollPane();
        alamatInputTextField = new javax.swing.JTextArea();
        simpanPenitipButton = new javax.swing.JButton();
        penitipScrollPane = new javax.swing.JScrollPane();
        penitipTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPenitipInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPenitipInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPenitipInputLabel.setText("Pencarian Penitip");

        searchPenitipInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        searchPenitipInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPenitipInputTextFieldKeyTyped(evt);
            }
        });

        searchPenitipInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchPenitipInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPenitipInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPenitipInputButton.setText("Cari");
        searchPenitipInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPenitipInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPenitipInputPanelLayout = new javax.swing.GroupLayout(searchPenitipInputPanel);
        searchPenitipInputPanel.setLayout(searchPenitipInputPanelLayout);
        searchPenitipInputPanelLayout.setHorizontalGroup(
            searchPenitipInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPenitipInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPenitipInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPenitipInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPenitipInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPenitipInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPenitipInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchPenitipInputPanelLayout.setVerticalGroup(
            searchPenitipInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPenitipInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPenitipInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPenitipInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPenitipInputTextField)
                    .addComponent(searchPenitipInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        penitipFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        penitipButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanPenitipButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPenitipButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanPenitipButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPenitipButton.setText("Barukan");
        barukanPenitipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPenitipButtonActionPerformed(evt);
            }
        });

        hapusPenitipButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPenitipButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusPenitipButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPenitipButton.setText("Hapus");
        hapusPenitipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPenitipButtonActionPerformed(evt);
            }
        });

        tambahPenitipButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPenitipButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahPenitipButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPenitipButton.setText("Tambah");
        tambahPenitipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPenitipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout penitipButtonPanelLayout = new javax.swing.GroupLayout(penitipButtonPanel);
        penitipButtonPanel.setLayout(penitipButtonPanelLayout);
        penitipButtonPanelLayout.setHorizontalGroup(
            penitipButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPenitipButton)
                .addGap(18, 18, 18)
                .addComponent(barukanPenitipButton)
                .addGap(18, 18, 18)
                .addComponent(hapusPenitipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        penitipButtonPanelLayout.setVerticalGroup(
            penitipButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penitipButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanPenitipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPenitipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusPenitipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPenitipPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaPenitipInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPenitipInputLabel.setText("Nama Penitip");

        namaPenitipInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        namaPenitipInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPenitipInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPenitipPanelLayout = new javax.swing.GroupLayout(namaPenitipPanel);
        namaPenitipPanel.setLayout(namaPenitipPanelLayout);
        namaPenitipPanelLayout.setHorizontalGroup(
            namaPenitipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPenitipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPenitipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPenitipInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPenitipInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPenitipPanelLayout.setVerticalGroup(
            namaPenitipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPenitipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPenitipInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPenitipInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorTeleponInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorTeleponInputPanelLayout = new javax.swing.GroupLayout(nomorTeleponInputPanel);
        nomorTeleponInputPanel.setLayout(nomorTeleponInputPanelLayout);
        nomorTeleponInputPanelLayout.setHorizontalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nomorTeleponInputPanelLayout.setVerticalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alamatInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        alamatInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel.setText("Alamat");

        alamatInputTextField.setColumns(20);
        alamatInputTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        alamatInputTextField.setRows(5);
        alamatScrollPane.setViewportView(alamatInputTextField);

        javax.swing.GroupLayout alamatInputPanelLayout = new javax.swing.GroupLayout(alamatInputPanel);
        alamatInputPanel.setLayout(alamatInputPanelLayout);
        alamatInputPanelLayout.setHorizontalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alamatInputPanelLayout.createSequentialGroup()
                        .addComponent(alamatInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addComponent(alamatScrollPane))
                .addContainerGap())
        );
        alamatInputPanelLayout.setVerticalGroup(
            alamatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout penitipFormPanelLayout = new javax.swing.GroupLayout(penitipFormPanel);
        penitipFormPanel.setLayout(penitipFormPanelLayout);
        penitipFormPanelLayout.setHorizontalGroup(
            penitipFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penitipFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penitipFormPanelLayout.createSequentialGroup()
                        .addComponent(penitipButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(penitipFormPanelLayout.createSequentialGroup()
                        .addGroup(penitipFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPenitipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(alamatInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        penitipFormPanelLayout.setVerticalGroup(
            penitipFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penitipFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penitipButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(penitipFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(penitipFormPanelLayout.createSequentialGroup()
                        .addComponent(namaPenitipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alamatInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanPenitipButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanPenitipButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanPenitipButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPenitipButton.setText("Simpan");
        simpanPenitipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPenitipButtonActionPerformed(evt);
            }
        });

        penitipScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        penitipTextArea.setColumns(20);
        penitipTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        penitipTextArea.setRows(5);
        penitipScrollPane.setViewportView(penitipTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPenitipInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(penitipFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addComponent(simpanPenitipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(penitipScrollPane))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPenitipInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(penitipFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanPenitipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(penitipScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPenitipInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPenitipInputTextFieldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n'){
            doSearchCustomer();
        }
    }//GEN-LAST:event_searchPenitipInputTextFieldKeyTyped

    private void searchPenitipInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPenitipInputButtonActionPerformed
        // TODO add your handling code here:
        doSearchCustomer();
    }//GEN-LAST:event_searchPenitipInputButtonActionPerformed

    private void barukanPenitipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPenitipButtonActionPerformed
        // TODO add your handling code here:

        actionCustomer = "update";
        setComponentsData(true);
    }//GEN-LAST:event_barukanPenitipButtonActionPerformed

    private void hapusPenitipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPenitipButtonActionPerformed
        // TODO add your handling code here:
        clearTextData();
        setEditDeleteButtonData(false);
        setComponentsData(false);

        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idCustomer = -1;
            return;
        }

        dataControl.deleteDataCustomer(idCustomer);
        
        idCustomer = -1;
        showCustomer();
    }//GEN-LAST:event_hapusPenitipButtonActionPerformed

    private void tambahPenitipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPenitipButtonActionPerformed
        // TODO add your handling code here:

        actionCustomer = "add";
        clearTextData();
        setEditDeleteButtonData(true);
        setComponentsData(true);
    }//GEN-LAST:event_tambahPenitipButtonActionPerformed

    private void namaPenitipInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPenitipInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPenitipInputTextFieldActionPerformed

    private void simpanPenitipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPenitipButtonActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionCustomer + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION)
        return;
        
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionCustomer + "?") == JOptionPane.CLOSED_OPTION)
            return;
            switch(actionCustomer){
                case "add":
                dataModel = new Karyawan(namaPenitipInputTextField.getText(), nomorTeleponInputTextField.getText(), alamatInputTextField.getText());
                dataControl.insertDataPenitip(dataModel);
                clearTextData();
                setEditDeleteButtonData(false);
                setComponentsData(false);
                break;
                
                case "update":
                dataModel = new Karyawan(namaPenitipInputTextField.getText(), nomorTeleponInputTextField.getText(), alamatInputTextField.getText());
                dataControl.updateDataCustomer(dataModel, idCustomer);
                clearTextData();
                setEditDeleteButtonData(false);
                setComponentsData(false);
                break;
                default:
                break;
            }
            showCustomer();
            actionCustomer = null;
    }//GEN-LAST:event_simpanPenitipButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatInputLabel;
    private javax.swing.JPanel alamatInputPanel;
    private javax.swing.JTextArea alamatInputTextField;
    private javax.swing.JScrollPane alamatScrollPane;
    private javax.swing.JButton barukanPenitipButton;
    private javax.swing.JButton hapusPenitipButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaPenitipInputLabel;
    private javax.swing.JTextField namaPenitipInputTextField;
    private javax.swing.JPanel namaPenitipPanel;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JPanel nomorTeleponInputPanel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JPanel penitipButtonPanel;
    private javax.swing.JPanel penitipFormPanel;
    private javax.swing.JScrollPane penitipScrollPane;
    private javax.swing.JTextArea penitipTextArea;
    private javax.swing.JButton searchPenitipInputButton;
    private javax.swing.JLabel searchPenitipInputLabel;
    private javax.swing.JPanel searchPenitipInputPanel;
    private javax.swing.JTextField searchPenitipInputTextField;
    private javax.swing.JButton simpanPenitipButton;
    private javax.swing.JButton tambahPenitipButton;
    // End of variables declaration//GEN-END:variables
}
