/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.PenitipControl;
import control.ProdukControl;
import control.PenitipanControl;



import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;

import model.Penitip;
import model.Produk;
import model.Penitipan;

public class PenitipanMainPanel extends javax.swing.JPanel {
    
    private PenitipControl singleDataControl;
    private ProdukControl multiDataControl;
    private PenitipanControl junctionControl;
    
    private Penitipan data = null;
    String action = null;
    int selectedId = 0;
    
    List<Penitip> singleList;
    List<Produk> multiList;

    private Component rootPane;
    
    // DROPDOWN 
    // KENDARAAN
    public void setKendaraanToDropdown(){
        multiList = multiDataControl.showListProduk();
        System.out.println(multiList.size());
        for(int i = 0; i < multiList.size(); i++){
            namaData2Dropdown.addItem(multiList.get(i));
            System.out.println(multiList.get(i).getNama());
        }
    }

    // CUSTOMER
    public void setCustomerToDropdown(){
        singleList = singleDataControl.showListPenitip();
        for(int i = 0; i < singleList.size(); i++){
            namaData1Dropdown.addItem(singleList.get(i));
        }
    }
    // DROPDOWN
    
    // RADIO BUTTON
    public void setRadioButtonValue(){
        radioData1.setActionCommand("Pending");
        radioData2.setActionCommand("In Progress");
        radioData3.setActionCommand("Completed");
    }
    // RADIO BUTTON
    
    // TABLE SHOW    
    public void showTableBySearch(String target){
        tableData.setModel(junctionControl.showTable(target));
    }
    // TABLE SHOW    

    // EXCEPTION
   

    // RESET METHOD TO DEFAULT
    public void clearText(){
        // RESET DROPDOWN
        namaData1Dropdown.setSelectedIndex(-1);
        namaData2Dropdown.setSelectedIndex(-1);
        
        // RESET CHECKBOX
        checkboxData1.setSelected(false);
        checkboxData2.setSelected(false);
        checkboxData3.setSelected(false);
        
        // RESET RADIOBUTTON
        radioButtonGroup.clearSelection();
        
        // RESET TEXT
        searchInput.setText("");
        dataInput1.setText("");
        dataInput2.setText("");
    }
    
    // SET METHOD BUTTON EDIT & DELETE
    public void setEditDeleteBtn(boolean value){
        barukanButton.setEnabled(value);
        hapusButton.setEnabled(value);
    }
    
    // METHOD FOR SET COMPONENT, ENABLE / DISABLE
    public void setComponent(boolean value){
        namaData1Dropdown.setEnabled(value);
        namaData2Dropdown.setEnabled(value);
        dataInput1.setEnabled(value);
        dataInput2.setEnabled(value);
        
        checkboxData1.setEnabled(value);
        checkboxData2.setEnabled(value);
        checkboxData3.setEnabled(value);
        
        saveButton.setEnabled(value);
        cancelButton.setEnabled(value);
    }

    // METHOD FOR SET RADIO BUTTON
    public void setRadioComponent(boolean value){
        radioData1.setEnabled(value);
        radioData2.setEnabled(value);
        radioData3.setEnabled(value);
    }
    
    public PenitipanMainPanel() {
        initComponents();
        setOpaque(false);     
        
        junctionControl = new PenitipanControl();
        singleDataControl = new PenitipControl();
        multiDataControl = new ProdukControl();
        
        setCustomerToDropdown();
        setKendaraanToDropdown();
        setRadioButtonValue();
        
        showTableBySearch("");
        
        // RESET
        clearText();
        setComponent(false);
        setRadioComponent(false);
        setEditDeleteBtn(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        searchInputPanel = new javax.swing.JPanel();
        searchInputLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        dataFormPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        barukanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        tambahDataButton = new javax.swing.JButton();
        data1Panel = new javax.swing.JPanel();
        namaData1Panel = new javax.swing.JLabel();
        namaData1Dropdown = new javax.swing.JComboBox<>();
        data2Panel = new javax.swing.JPanel();
        namaData2Panel = new javax.swing.JLabel();
        namaData2Dropdown = new javax.swing.JComboBox<>();
        checkboxPanel = new javax.swing.JPanel();
        checkboxLabel = new javax.swing.JLabel();
        checkboxData1 = new javax.swing.JCheckBox();
        checkboxData2 = new javax.swing.JCheckBox();
        checkboxData3 = new javax.swing.JCheckBox();
        radioPanel = new javax.swing.JPanel();
        radioLabel = new javax.swing.JLabel();
        radioData1 = new javax.swing.JRadioButton();
        radioData2 = new javax.swing.JRadioButton();
        radioData3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dataInput2 = new javax.swing.JTextField();
        dataInput1 = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInputLabel.setText("Pencarian Transaksi");

        searchInput.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchInputKeyPressed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(27, 26, 85));
        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        dataFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanButton.setText("Barukan");
        barukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        tambahDataButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahDataButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahDataButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahDataButton.setText("Tambah");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(barukanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        data1Panel.setBackground(new java.awt.Color(255, 255, 255));

        namaData1Panel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaData1Panel.setText("Nama Penitip");

        namaData1Dropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout data1PanelLayout = new javax.swing.GroupLayout(data1Panel);
        data1Panel.setLayout(data1PanelLayout);
        data1PanelLayout.setHorizontalGroup(
            data1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaData1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaData1Dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        data1PanelLayout.setVerticalGroup(
            data1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaData1Panel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaData1Dropdown, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        data2Panel.setBackground(new java.awt.Color(255, 255, 255));

        namaData2Panel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaData2Panel.setText("Nama Produk");

        namaData2Dropdown.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout data2PanelLayout = new javax.swing.GroupLayout(data2Panel);
        data2Panel.setLayout(data2PanelLayout);
        data2PanelLayout.setHorizontalGroup(
            data2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaData2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaData2Dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        data2PanelLayout.setVerticalGroup(
            data2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaData2Panel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaData2Dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        checkboxPanel.setBackground(new java.awt.Color(255, 255, 255));

        checkboxLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        checkboxLabel.setText("Catatan");

        checkboxData1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        checkboxData1.setText("Simpan suhu ruangan");

        checkboxData2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        checkboxData2.setText("Jangan diguncang");

        checkboxData3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        checkboxData3.setText("Tidak boleh dibalik");

        javax.swing.GroupLayout checkboxPanelLayout = new javax.swing.GroupLayout(checkboxPanel);
        checkboxPanel.setLayout(checkboxPanelLayout);
        checkboxPanelLayout.setHorizontalGroup(
            checkboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkboxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(checkboxPanelLayout.createSequentialGroup()
                        .addGroup(checkboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxData1)
                            .addComponent(checkboxData2)
                            .addComponent(checkboxData3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        checkboxPanelLayout.setVerticalGroup(
            checkboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkboxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxData2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radioPanel.setBackground(new java.awt.Color(255, 255, 255));

        radioLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioLabel.setText("Status");

        radioButtonGroup.add(radioData1);
        radioData1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData1.setText("Pending");

        radioButtonGroup.add(radioData2);
        radioData2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData2.setText("In Progress");

        radioButtonGroup.add(radioData3);
        radioData3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        radioData3.setText("Completed");

        javax.swing.GroupLayout radioPanelLayout = new javax.swing.GroupLayout(radioPanel);
        radioPanel.setLayout(radioPanelLayout);
        radioPanelLayout.setHorizontalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLabel)
                    .addComponent(radioData1)
                    .addComponent(radioData2)
                    .addComponent(radioData3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        radioPanelLayout.setVerticalGroup(
            radioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel1.setText("Tanggal Titipan");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah Titipan");

        dataInput2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dataInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dataInput1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        dataInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInput1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataFormPanelLayout = new javax.swing.GroupLayout(dataFormPanel);
        dataFormPanel.setLayout(dataFormPanelLayout);
        dataFormPanelLayout.setHorizontalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(checkboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataFormPanelLayout.setVerticalGroup(
            dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(radioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dataFormPanelLayout.createSequentialGroup()
                            .addComponent(data1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(data2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(checkboxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchInputPanelLayout = new javax.swing.GroupLayout(searchInputPanel);
        searchInputPanel.setLayout(searchInputPanelLayout);
        searchInputPanelLayout.setHorizontalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchInputPanelLayout.createSequentialGroup()
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(dataFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchInputPanelLayout.setVerticalGroup(
            searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInput)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setBackground(new java.awt.Color(51, 178, 73));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(237, 8, 0));
        cancelButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batalkan");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyPressed

    }//GEN-LAST:event_searchInputKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        showTableBySearch(searchInput.getText());
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        radioButtonGroup.clearSelection();
        tambahDataButton.setEnabled(true);      
    }//GEN-LAST:event_searchButtonActionPerformed

    private void barukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanButtonActionPerformed
        action = "baharui";
        setComponent(true);
        namaData1Dropdown.setEnabled(false);
        setEditDeleteBtn(true);
        setRadioComponent(false);  
    }//GEN-LAST:event_barukanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        action = "hapus";
        
        if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + action + "?") == JOptionPane.CLOSED_OPTION)
        return;

        junctionControl.deleteData(selectedId);
        
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        radioButtonGroup.clearSelection();
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        action = "tambah";
        setComponent(true);
        setRadioComponent(true); 
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
            
            // SET ATRIBUT DAN METODE PEMBAYARAN
            int counter = 0;
            String checkbox = "";
            String radio = "";
            
            // MENCARI INDEX YANG DITUNJUK OLEH DROPDOWN
            // CUSTOMER
            int selectedIndexSingle = namaData1Dropdown.getSelectedIndex();            
            Penitip selectedSingle = singleList.get(selectedIndexSingle);
            
            // KENDARAAN
            int selectedIndexMulti = namaData2Dropdown.getSelectedIndex();
            Produk selectedMulti = multiList.get(selectedIndexMulti);
            
            if(checkboxData1.isSelected() && checkboxData2.isSelected() && checkboxData3.isSelected()){
                checkbox = "Berhati-hati dengan produk ini!";
            }else{
                if(checkboxData1.isSelected()){
                    checkbox += "Simpan pada suhu ruang";
                    counter++;                    
                }
                
                if(checkboxData2.isSelected()){
                    if(counter == 0){
                        checkbox += "Jangan diguncang";
                    }else{
                        checkbox += ", jangan diguncang";
                    }
                    counter++;
                }
                
                if(checkboxData3.isSelected()){
                    if(counter == 0){
                        checkbox += "Tidak boleh dibalik";
                    }else{
                        checkbox += ", tidak boleh dibalik";
                    }
                }
            }
            
            radio = radioButtonGroup.getSelection().getActionCommand();
            
            if(action.equals("tambah")){
                Penitipan dataNew = new Penitipan(selectedSingle.getId_penitip(), selectedMulti.getId_produk(), checkbox, 
                    radio, dataInput1.getText(), Integer.parseInt(dataInput2.getText()), selectedSingle, selectedMulti);
                junctionControl.insertData(dataNew);
            } else {
                Penitipan dataNew = new Penitipan(selectedSingle.getId_penitip(), selectedMulti.getId_produk(), checkbox, 
                    radio, dataInput1.getText(), Integer.parseInt(dataInput2.getText()), selectedSingle, selectedMulti);
                junctionControl.updateData(dataNew, selectedId);
                selectedId = -1;
            }
        
                
        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        radioButtonGroup.clearSelection();
        tambahDataButton.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearText();
        setEditDeleteBtn(false);
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        tambahDataButton.setEnabled(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int indexSingle = -1, indexMulti = -1;
        action = "baharui";
        
        tambahDataButton.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);        
        setEditDeleteBtn(true);
        
        setComponent(false);
        setRadioComponent(false);        
        radioButtonGroup.clearSelection();
        
        int clickedRow = tableData.getSelectedRow();
        TableModel tableModel = tableData.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 9).toString());

        dataInput1.setText(tableModel.getValueAt(clickedRow, 6).toString());
        dataInput2.setText(tableModel.getValueAt(clickedRow, 5).toString());
        
        String checkbox = tableModel.getValueAt(clickedRow, 3).toString();                
        String radio = tableModel.getValueAt(clickedRow, 4).toString();

        switch(radio){
            case "Pending" :
                radioData1.setSelected(true);
                break;
            case "In Progress" :
                radioData2.setSelected(true);
                break;
            case "Completed":
                radioData3.setSelected(true);
                break;
        }
        
        checkboxData1.setSelected(false);
        checkboxData2.setSelected(false);
        checkboxData3.setSelected(false);
        
        switch(checkbox){
            case "Simpan pada suhu ruang" :
                checkboxData1.setSelected(true);
                break;
            case "Jangan diguncang" :
                checkboxData2.setSelected(true);
                break;
            case "Tidak boleh dibalik" :
                checkboxData3.setSelected(true);
                break;
            case "Berhati-hati dengan produk ini!" :
                checkboxData1.setSelected(true);
                checkboxData2.setSelected(true);
                checkboxData3.setSelected(true);
                break;
            case "Simpan pada suhu ruang, jangan diguncang" :
                checkboxData1.setSelected(true);
                checkboxData2.setSelected(true);
                break;
            case "Simpan pada suhu ruang, tidak boleh dibalik" :
                checkboxData1.setSelected(true);
                checkboxData3.setSelected(true);
                break;
            case "Jangan diguncang, tidak boleh dibalik" :
                checkboxData2.setSelected(true);
                checkboxData3.setSelected(true);
                break;
        }

        for(Penitip first : singleList){
            if(first.getId_penitip() == Integer.parseInt(tableModel.getValueAt(clickedRow, 7).toString())){
                indexSingle = singleList.indexOf(first);
            }
        }
        
        for(Produk second : multiList){
            if(second.getId_produk().equals(tableModel.getValueAt(clickedRow, 8).toString())){
                indexMulti = multiList.indexOf(second);
            }
        }        
        
        namaData1Dropdown.setSelectedIndex(indexSingle);
        namaData2Dropdown.setSelectedIndex(indexMulti);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_tableDataMouseClicked

    private void dataInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInput1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox checkboxData1;
    private javax.swing.JCheckBox checkboxData2;
    private javax.swing.JCheckBox checkboxData3;
    private javax.swing.JLabel checkboxLabel;
    private javax.swing.JPanel checkboxPanel;
    private javax.swing.JPanel data1Panel;
    private javax.swing.JPanel data2Panel;
    private javax.swing.JPanel dataFormPanel;
    private javax.swing.JTextField dataInput1;
    private javax.swing.JTextField dataInput2;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<Penitip> namaData1Dropdown;
    private javax.swing.JLabel namaData1Panel;
    private javax.swing.JComboBox<Produk> namaData2Dropdown;
    private javax.swing.JLabel namaData2Panel;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JRadioButton radioData1;
    private javax.swing.JRadioButton radioData2;
    private javax.swing.JRadioButton radioData3;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JPanel radioPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel searchInputLabel;
    private javax.swing.JPanel searchInputPanel;
    private javax.swing.JTable tableData;
    private javax.swing.JButton tambahDataButton;
    // End of variables declaration//GEN-END:variables
}
